blank_issues_enabled: false
contact_links:
  - name: Questions and ideas
    url: https://github.com/dzweben/personal-aiagent/discussions
    about: for open ended questions, use discussions instead of an issue.
