"""the toolsmith: the agent writes its own tools.

this is the slightly unhinged one. given a name, a description, and a python expression (or
an llm to dream one up), `forge()` generates a real plugin module, runs it through an ast
safety check, writes it into the plugin dir, and hot-loads it -- so a brand new tool shows up
in the live tool belt without restarting anything. it closes the loop with agent/plugins.py:
the agent can grow its own abilities at runtime.

the scary part is obviously "run generated code", so the whole thing is built around a
deliberately paranoid validator. generated source may only import from a small allowlist, may
not touch os / sys / subprocess / sockets, may not call eval / exec / open / __import__, and
may not poke at dunder attributes. anything outside that raises SafetyError before a single
line is written to disk, let alone imported. it is still a toy -- do not point it at hostile
input -- but it is a toy with a seatbelt on.
"""

from __future__ import annotations

import ast
import keyword
import re
from pathlib import Path

from agent.logging_utils import get_logger
from agent.plugins import load_plugins, plugin_dir

log = get_logger(__name__)

# modules a generated tool is allowed to lean on. small on purpose.
ALLOWED_IMPORTS = frozenset(
    {"math", "random", "datetime", "json", "re", "statistics", "textwrap", "string"}
)

# names that never get to appear in generated source, full stop.
FORBIDDEN_NAMES = frozenset(
    {
        "os",
        "sys",
        "subprocess",
        "socket",
        "shutil",
        "pathlib",
        "open",
        "eval",
        "exec",
        "compile",
        "__import__",
        "globals",
        "locals",
        "vars",
        "getattr",
        "setattr",
        "delattr",
        "input",
        "breakpoint",
        "exit",
        "quit",
        "memoryview",
        "help",
    }
)


class SafetyError(ValueError):
    """raised when generated source trips the sandbox checks."""


def _check_name(name: str) -> None:
    if name in FORBIDDEN_NAMES:
        raise SafetyError(f"use of {name!r} is not allowed in a forged tool")
    if name.startswith("__") and name.endswith("__"):
        raise SafetyError(f"dunder name {name!r} is not allowed in a forged tool")


def validate_source(source: str) -> None:
    """walk the ast and refuse anything outside the sandbox. raises SafetyError if unhappy."""
    try:
        tree = ast.parse(source)
    except SyntaxError as exc:  # pragma: no cover - rendering shouldn't emit bad syntax
        raise SafetyError(f"generated source does not parse: {exc}") from exc

    for node in ast.walk(tree):
        # only allow imports from the allowlist
        if isinstance(node, ast.Import):
            for alias in node.names:
                root = alias.name.split(".")[0]
                if root not in ALLOWED_IMPORTS and alias.name != "langchain.tools":
                    raise SafetyError(f"import of {alias.name!r} is not allowed")
        elif isinstance(node, ast.ImportFrom):
            root = (node.module or "").split(".")[0]
            if root not in ALLOWED_IMPORTS and node.module not in (
                "langchain.tools",
                "agent.tools",
                "__future__",
            ):
                raise SafetyError(f"import from {node.module!r} is not allowed")
        # block dangerous identifiers wherever they show up
        elif isinstance(node, ast.Name):
            _check_name(node.id)
        elif isinstance(node, ast.Attribute):
            _check_name(node.attr)


def _safe_slug(name: str) -> str:
    slug = re.sub(r"[^0-9a-zA-Z_]", "_", name.strip().lower()).strip("_")
    if not slug or keyword.iskeyword(slug) or slug[0].isdigit():
        raise SafetyError(f"{name!r} is not a usable tool name")
    return slug


_MODULES_RE = re.compile(r"\b([a-z_]+)\b")


def _imports_for(expr: str) -> list[str]:
    """figure out which allowlisted modules the expression actually mentions, import only those."""
    used = {m for m in _MODULES_RE.findall(expr) if m in ALLOWED_IMPORTS}
    return sorted(used)


def render_plugin(name: str, description: str, expr: str) -> str:
    """build plugin source for a tool whose body is `return str(<expr>)`, with `x` as the input.

    `x` is the raw string the agent passes the tool. the expression is dropped in verbatim, so
    keep it to the safe subset -- it gets validated before anything is written or imported.
    """
    slug = _safe_slug(name)
    desc = description.replace('"', "'").strip() or f"the {slug} tool"
    imports = _imports_for(expr)
    import_line = ("import " + ", ".join(imports) + "\n") if imports else ""
    # a tidy, lint-clean module in the same shape as a hand-written plugin
    source = (
        '"""auto-generated by the toolsmith (agent/forge.py). edit or delete freely."""\n\n'
        "from __future__ import annotations\n\n"
        f"{import_line}"
        "from langchain.tools import Tool\n\n"
        "from agent.tools import register\n\n\n"
        f"def _run(x: str) -> str:\n"
        f"    # {desc}\n"
        f"    return str({expr})\n\n\n"
        f'@register("{slug}")\n'
        f"def _factory():\n"
        f'    return Tool(name="{slug}", description="{desc} Input: a single value as text.",'
        f" func=_run)\n"
    )
    return source


def render_plugin_body(name: str, description: str, body: str) -> str:
    """build plugin source from a multi-statement function body (must `return` a value).

    unlike render_plugin (one expression), this lets a forged tool use locals, conditionals, and
    loops -- the body is indented under `def _run(x):`. it's still sandbox-checked before use.
    """
    slug = _safe_slug(name)
    desc = description.replace('"', "'").strip() or f"the {slug} tool"
    imports = _imports_for(body)
    import_line = ("import " + ", ".join(imports) + "\n") if imports else ""
    indented = "\n".join(f"    {line}" if line.strip() else "" for line in body.splitlines())
    source = (
        '"""auto-generated by the toolsmith (agent/forge.py). edit or delete freely."""\n\n'
        "from __future__ import annotations\n\n"
        f"{import_line}"
        "from langchain.tools import Tool\n\n"
        "from agent.tools import register\n\n\n"
        f"def _run(x: str) -> str:\n"
        f"    # {desc}\n"
        f"{indented}\n\n\n"
        f'@register("{slug}")\n'
        f"def _factory():\n"
        f'    return Tool(name="{slug}", description="{desc} Input: a single value as text.",'
        f" func=_run)\n"
    )
    return source


def forge(
    name: str,
    description: str,
    expr: str | None = None,
    *,
    body: str | None = None,
    directory: Path | None = None,
    overwrite: bool = False,
) -> Path:
    """generate, sandbox-check, write, and hot-load a new tool. returns the file path.

    pass `expr` for a one-expression tool (`return str(<expr>)`) or `body` for a full
    multi-statement function body (which must `return`). exactly one of the two is required.

    raises SafetyError if the generated code is unsafe, FileExistsError if the plugin already
    exists and overwrite is False, and RuntimeError if the tool fails to register after loading.
    """
    if (expr is None) == (body is None):
        raise SafetyError("forge needs exactly one of expr= or body=")
    slug = _safe_slug(name)
    source = (
        render_plugin(name, description, expr)
        if expr is not None
        else render_plugin_body(name, description, body)
    )
    validate_source(source)  # paranoia before we touch the disk

    directory = directory or plugin_dir()
    directory.mkdir(parents=True, exist_ok=True)
    target = directory / f"{slug}.py"
    if target.exists() and not overwrite:
        raise FileExistsError(f"{target} already exists (pass overwrite=True to replace it)")
    target.write_text(source, encoding="utf-8")
    log.info("forged new tool %r at %s", slug, target)

    # hot-load and confirm it actually registered
    load_plugins(directory)
    from agent.tools import available_tool_names

    if slug not in available_tool_names():
        raise RuntimeError(f"forged {slug!r} but it did not register; check the generated source")
    return target


def _is_forged(path: Path) -> bool:
    try:
        return path.read_text(encoding="utf-8").startswith('"""auto-generated by the toolsmith')
    except OSError:
        return False


def list_forged(directory: Path | None = None) -> list[str]:
    """return the names of tools that were created by the toolsmith (not hand-written ones)."""
    directory = directory or plugin_dir()
    if not directory.is_dir():
        return []
    return sorted(p.stem for p in directory.glob("*.py") if _is_forged(p))


def remove_forged(name: str, directory: Path | None = None) -> bool:
    """delete a forged tool's file. refuses to touch a plugin it didn't generate. returns True
    if a file was removed."""
    slug = _safe_slug(name)
    directory = directory or plugin_dir()
    target = directory / f"{slug}.py"
    if not target.exists():
        return False
    if not _is_forged(target):
        raise SafetyError(f"{target} wasn't created by the toolsmith; refusing to delete it")
    target.unlink()
    log.info("removed forged tool %r", slug)
    return True


_FENCE_BLOCK_RE = re.compile(r"```[a-zA-Z]*\n(.*?)```", re.DOTALL)

_DRAFT_SYSTEM = (
    "You write the body of a tiny Python tool. The user describes what it should do. "
    "Reply with ONLY a single Python expression (no statements, no imports, no code fences) "
    "that computes the result from a variable `x` (a string the caller passes in). "
    "You may use these modules without importing them: math, random, datetime, json, re, "
    "statistics, textwrap, string. You may NOT use os, sys, subprocess, eval, exec, open, "
    "__import__, or any dunder attribute. Example reply for 'double a number': float(x) * 2"
)


def draft_expr(intent: str, complete=None, settings=None) -> str:
    """ask an llm to write a safe one-line expression for the given intent.

    `complete` is injectable (a callable taking a prompt) so this is testable without a live
    model; by default it routes through agent.llm.complete. the result is still validated by
    forge() before anything runs, so a misbehaving model can't get unsafe code past the gate.
    """
    if complete is None:
        from agent.llm import complete as _default_complete

        def complete(prompt: str) -> str:  # noqa: A001 - shadow on purpose, local default
            return _default_complete(prompt, settings=settings, system=_DRAFT_SYSTEM)

    raw = complete(f"Write the tool body for: {intent}")
    # if the model fenced its answer, take what's inside the fence; otherwise use the whole reply
    fenced = _FENCE_BLOCK_RE.search(raw)
    candidate = fenced.group(1) if fenced else raw
    # collapse to the first non-empty line; the model sometimes adds a trailing comment
    expr = next((ln.strip() for ln in candidate.splitlines() if ln.strip()), "")
    if not expr:
        raise SafetyError("the model returned an empty expression")
    return expr


def forge_from_intent(
    name: str,
    intent: str,
    *,
    complete=None,
    settings=None,
    directory: Path | None = None,
    overwrite: bool = False,
) -> tuple[Path, str]:
    """let the model dream up the expression from a plain-english intent, then forge it.

    returns (path, expr) so callers can show what the model actually wrote.
    """
    expr = draft_expr(intent, complete=complete, settings=settings)
    path = forge(name, intent, expr, directory=directory, overwrite=overwrite)
    return path, expr
